name: easycut_business
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cloud_firestore: ^4.17.5
  connectivity_plus: ^6.1.0
  country_picker: ^2.0.27
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.7.0
  dots_indicator: ^3.0.0
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^17.2.2
  flutter_screenutil: ^5.9.3
  flutter_timezone: ^4.1.0
  get: ^4.6.5
  http: ^1.2.2
  image_picker: ^1.0.3
  intl: ^0.18.1
  logger: ^2.1.0
  lottie: ^2.3.2
  path_provider: ^2.1.5
  shared_preferences: ^2.2.0
  syncfusion_flutter_charts: ^29.1.38


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
    - assets/images/salonbk/
    - assets/images/icon/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
