Map<String, String> langEn = {
  '1': 'Choose Language',
  '2': 'Arabic',
  '3': 'English',
  '4': 'German',
  '5': 'Easy Cut',
  '6': 'Start with us is very easy \nWe save your Time',
  '7': 'Booking Now',
  '8': 'Book any time. \nwe serve the nearest salon for you.',
  '9': 'Track Receipment',
  '10': 'You can now access your payments \nand have access to buy products.',
  '11': 'List Products',
  '12': 'You can buy any product \n from your salon.',
  '13': 'Continue',
  '14': 'Welcome',
  '15': 'Happy to see you,',
  '16': 'Login Now and Save your Time.',
  '17': 'Email',
  '18': 'Password',
  '19': 'Forget Password?',
  '20': 'Login',
  '21': "Don't have an account?",
  '22': 'Register',
  '23': 'Forget Password',
  '24': "Don't worry, it happens,",
  '25': 'Please, Enter your Email Address.',
  '26': 'Check Email',
  '27': 'PIN Code',
  '28': "Please, Check your Email, we've sent PIN code to",
  '29': 'Full Number',
  '30': 'Reset Password',
  '31': 'Congratulation',
  '32': 'Please, Enter new Password',
  '33': 'Re-Enter Password',
  '34': 'Go to Login',
  '35': 'Full Name',
  '36': 'Phone Number',
  '37': 'Have an account?',
  '38': 'Gender',
  '39': 'Male',
  '40': 'Female',
  '41': 'Name not valid',
  '42': 'Email not valid',
  '43': 'Phone not valid',
  '44': "Can't be Empty",
  '45': "Can't be less than",
  '46': "Can't be greater than",
  '47': "Alert!",
  '48': 'Do you want exit App?',
  '49': 'Yes',
  '50': 'No',
  '51': '',
  '52': '',
  '53': '',
  '54': '',
  '55': '',
  '56': '',
  '57': '',
  '58': '',
  '59': '',
  '60': '',
  '61': '',
  '62': '',
  '63': '',
  '64': '',
  '65': '',
  '66': '',
  '67': '',
  '68': '',
  '69': '',
  '70': '',
  '71': '',
  '72': '',
  '73': '',
  '74': '',
  '75': '',
  '76': '',
  '77': '',
  '78': '',
  '79': '',
  '80': '',
  '81': '',
  '82': '',
  '83': '',
  '84': '',
  '85': '',
  '86': '',
  '87': '',
  '88': '',
  '89': '',
  '90': '',
  '91': '',
  '92': '',
  '93': '',
  '94': '',
  '95': '',
  '96': '',
  '97': '',
  '98': '',
  '99': '',
};
